##############################################
#               MY PLUGINS                   #
##############################################

plugins:
  mogi:
    executor: central_deployment_agent
    source: https://github.com/guy-mograbi-at-gigaspaces/cloudify3-plugins/archive/master.zip


node_types:
  mogi.Echo:
    derived_from: cloudify.nodes.Root
    properties:
      message:
        default: 'show me the money'
        description: >
          Say what you want to the world
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: mogi.lib.echo.create

